<a href="https://colab.research.google.com/github/FrankAlvaradoR/Teor-a-de-Control/blob/main/4_Solucion_de_ecuaciones.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Solución de Ecuaciones

Ejemplo: Para resolver el siguiente sistema de ecuaciones:

4x  + 3y = 20
 
-5x + 9y = 26



In [6]:
#Solución de un sistema de ecuaciones

import numpy as np

m_list = [[4, 3], [-5, 9]]
A = np.array(m_list)
inv_A = np.linalg.inv(A)

print(inv_A)

B = np.array([20, 26])
X = np.linalg.inv(A).dot(B)

print("\n el primer valor es la solución de x, el segundo de y")
print("\n",X)

[[ 0.17647059 -0.05882353]
 [ 0.09803922  0.07843137]]

 el primer valor es la solución de x, el segundo de y

 [2. 4.]


Ejemplo: Para resolver el siguiente sistema de ecuaciones:

 4x + 3y + 2z = 25  

-2x + 2y + 3z = -10

 3x - 5y + 2z = -4

In [7]:
#Solución de un sistema de ecuaciones 3 incognitas
import numpy as np
A = np.array([[4, 3, 2], [-2, 2, 3], [3, -5, 2]])
B = np.array([25, -10, -4])
X = np.linalg.inv(A).dot(B)

print(X)

[ 5.  3. -2.]


In [8]:
#Otra opción para resolver el mismo ejercicio sería: 
A = np.array([[4, 3, 2], [-2, 2, 3], [3, -5, 2]])
B = np.array([25, -10, -4])
X2 = np.linalg.solve(A,B)

print(X2)

[ 5.  3. -2.]
